# Generated by Django 4.2.6 on 2024-01-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_alter_booking_passengers_alter_booking_user_and_more'),
    ]

    operations = [
    ]
