# Generated by Django 4.2.6 on 2024-01-08 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_auto_20240108_1521'),
    ]

    operations = [
    ]
